### ISSUE TITLE
The app UI is only in the native language it was built 

### ISSUE THREAD

**Issue by valhallanow** [Schneppi/Stable-Diffusion-Prompter#4]
I love this app and will keep using it but the UI for interacting with export import is only in the native language. Only posting because the app is so great and want to help you improve it for broader use. 
![Screenshot 2023-11-24 at 10 13 45 AM](https://github.com/Schneppi/Stable-Diffusion-Prompter/assets/149092491/8c30b74a-d09b-4b49-b960-5970c001e758)

**Comment by Schneppi** [comment]
Should be fixed with Release 1.5.2.

Thank you for your support. 👍
